"""Public interface for the CHORM package."""

__version__ = "0.3.0"

from chorm.async_engine import AsyncConnection, AsyncEngine, create_async_engine
from chorm.async_pool import AsyncConnectionPool
from chorm.async_session import AsyncSession
from chorm.batch import (
    BatchDelete,
    BatchInsert,
    BatchUpdate,
    batch_delete,
    batch_insert,
    batch_update,
)
from chorm.batch_optimized import (
    DEFAULT_BATCH_SIZE,
    RECOMMENDED_MIN_BATCH,
    ClickHouseBatchInsert,
    ClickHouseBatchInsertFromDataFrame,
    bulk_insert,
)
from chorm.codecs import (
    FPC,
    LZ4,
    LZ4HC,
    T64,
    ZSTD,
    Codec,
    Delta,
    DoubleDelta,
    Gorilla,
)
from chorm.ddl import format_ddl
from chorm.declarative import Column, DeclarativeError, Table
from chorm.engine import Connection, Engine, EngineConfig, create_engine
from chorm.exceptions import (
    CHORMError,
    ConfigurationError,
    ConversionError,
    DatabaseAuthenticationError,
    DatabaseConnectionError,
    DatabaseError,
    DatabaseMemoryError,
    DatabaseStorageError,
    DatabaseSyntaxError,
    # Backward compatibility
    EngineConfigurationError,
    InvalidQueryError,
    MultipleResultsFound,
    NoResultFound,
    QueryError,
    QueryValidationError,
    ResultError,
    TypeConversionError,
    ValidationError,
)
from chorm.health import AsyncHealthCheck, HealthCheck
from chorm.metadata import MetaData
from chorm.metrics import (
    MetricsCollector,
    QueryMetrics,
    disable_global_metrics,
    enable_global_metrics,
    get_global_collector,
)
from chorm.pool import ConnectionPool
from chorm.profiler import QueryAnalyzer, QueryComplexity
from chorm.query_cache import (
    CachedQuery,
    QueryCache,
    disable_global_cache,
    enable_global_cache,
    get_global_cache,
)
from chorm.query_settings import (
    SETTINGS_PRESETS,
    ExecutionStats,
    QueryOptimizer,
    QuerySettings,
    get_preset,
)
from chorm.result import Result
from chorm.retry import RetryConfig, async_with_retry, with_retry
from chorm.session import Session
from chorm.sql import (
    Explain,
    add_column,
    add_index,
    attach_partition,
    create_dictionary,
    create_materialized_view,
    cte,
    delete,
    detach_partition,
    drop_column,
    drop_index,
    drop_partition,
    drop_table,
    fetch_partition,
    func,
    insert,
    modify_column,
    modify_ttl,
    optimize_table,
    rename_column,
    rename_table,
    select,
    text,
    truncate_table,
    update,
    window,
)
from chorm.table_engines import (
    ENGINE_CLASSES,
    JDBC,
    ODBC,
    AggregatingMergeTree,
    CollapsingMergeTree,
    Distributed,
    File,
    GraphiteMergeTree,
    Join,
    Kafka,
    Log,
    MaterializedView,
    Memory,
    MergeTree,
    MySQL,
    Null,
    PostgreSQL,
    ReplacingMergeTree,
    ReplicatedAggregatingMergeTree,
    ReplicatedCollapsingMergeTree,
    ReplicatedGraphiteMergeTree,
    ReplicatedMergeTree,
    ReplicatedReplacingMergeTree,
    ReplicatedSummingMergeTree,
    ReplicatedVersionedCollapsingMergeTree,
    Set,
    StripeLog,
    SummingMergeTree,
    TinyLog,
    VersionedCollapsingMergeTree,
    View,
)
from chorm.validators import (
    CustomValidator,
    EmailValidator,
    InValidator,
    LengthValidator,
    NotInValidator,
    RangeValidator,
    RegexValidator,
    Validator,
    validate_value,
)

__all__ = [
    "DEFAULT_BATCH_SIZE",
    # Table engines
    "ENGINE_CLASSES",
    "FPC",
    "JDBC",
    "LZ4",
    "LZ4HC",
    "ODBC",
    "RECOMMENDED_MIN_BATCH",
    "SETTINGS_PRESETS",
    "T64",
    "ZSTD",
    "AggregatingMergeTree",
    "AsyncConnection",
    "AsyncConnectionPool",
    "AsyncEngine",
    "AsyncHealthCheck",
    "AsyncSession",
    "BatchDelete",
    "BatchInsert",
    "BatchUpdate",
    # Exceptions
    "CHORMError",
    "CachedQuery",
    "ClickHouseBatchInsert",
    "ClickHouseBatchInsertFromDataFrame",
    # Codecs
    "Codec",
    "CollapsingMergeTree",
    "Column",
    "ConfigurationError",
    "Connection",
    "ConnectionPool",
    "ConversionError",
    "CustomValidator",
    "DatabaseAuthenticationError",
    "DatabaseConnectionError",
    "DatabaseError",
    "DatabaseMemoryError",
    "DatabaseStorageError",
    "DatabaseSyntaxError",
    "DeclarativeError",
    "Delta",
    "Distributed",
    "DoubleDelta",
    "EmailValidator",
    "Engine",
    "EngineConfig",
    "EngineConfigurationError",
    "ExecutionStats",
    "Explain",
    "File",
    "Gorilla",
    "GraphiteMergeTree",
    "HealthCheck",
    "InValidator",
    "InvalidQueryError",
    "Join",
    "Kafka",
    "LengthValidator",
    "Log",
    "MaterializedView",
    "Memory",
    "MergeTree",
    "MetaData",
    "MetricsCollector",
    "MultipleResultsFound",
    "MySQL",
    "NoResultFound",
    "NotInValidator",
    "Null",
    "PostgreSQL",
    "QueryAnalyzer",
    "QueryCache",
    "QueryComplexity",
    "QueryError",
    "QueryMetrics",
    "QueryOptimizer",
    "QuerySettings",
    "QueryValidationError",
    "RangeValidator",
    "RegexValidator",
    "ReplacingMergeTree",
    "ReplicatedAggregatingMergeTree",
    "ReplicatedCollapsingMergeTree",
    "ReplicatedGraphiteMergeTree",
    "ReplicatedMergeTree",
    "ReplicatedReplacingMergeTree",
    "ReplicatedSummingMergeTree",
    "ReplicatedVersionedCollapsingMergeTree",
    "Result",
    "ResultError",
    "RetryConfig",
    "Session",
    "Set",
    "StripeLog",
    "SummingMergeTree",
    "Table",
    "TinyLog",
    "TypeConversionError",
    "ValidationError",
    # Validators
    "Validator",
    "VersionedCollapsingMergeTree",
    "View",
    "__version__",
    "add_column",
    "add_index",
    "async_with_retry",
    "attach_partition",
    "batch_delete",
    "batch_insert",
    "batch_update",
    "bulk_insert",
    "create_async_engine",
    "create_dictionary",
    "create_engine",
    "create_materialized_view",
    "cte",
    "delete",
    "detach_partition",
    "disable_global_cache",
    "disable_global_metrics",
    "drop_column",
    "drop_index",
    "drop_partition",
    # DDL operations
    "drop_table",
    "enable_global_cache",
    "enable_global_metrics",
    "fetch_partition",
    "format_ddl",
    "func",
    "get_global_cache",
    "get_global_collector",
    "get_preset",
    "insert",
    "modify_column",
    "modify_ttl",
    "optimize_table",
    "rename_column",
    "rename_table",
    "select",
    "text",
    "truncate_table",
    "update",
    "validate_value",
    "window",
    "with_retry",
]
